:book: clarify documentation, add more examples
itpp-labs/sync-addons pull request #134
Opened 2020-04-24 23:10 UTC by trojikman

2020-04-25 06:49 UTC, yelizariev commented on openapi/doc/index.rst
> +* Open ``Allowed Integrations``, from here you can copy the token
Это уже есть выше

```

* Open menu ``[[ Settings ]] >> Users >> Users``
* Select a user that will be used for iteracting over API
* In **Allowed Integration** select some integrations
* Copy **OpenAPI Token** to use it in any system that support OpenAPI
```

2020-04-27 10:02 UTC, trojikman commented on openapi/doc/index.rst
> +* Open ``Allowed Integrations``, from here you can copy the token
Тут не понятно откуда его нужно брать. Я сам с этим столкнулся, когда в первый раз использовал.

2020-04-27 10:05 UTC, trojikman commented on openapi/doc/index.rst
> +* Open ``Allowed Integrations``, from here you can copy the token
Хотя да, почему то мимо этого заголовка постоянно проходил

2020-04-27 17:07 UTC, trojikman commented
Надо еще добавить про x2many

2020-04-28 12:51 UTC, trojikman commented
@yelizariev Посмотри, эту часть думаю можно добавить, насчет остального пока думаю что делать

2020-04-28 13:43 UTC, yelizariev requested changes

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +If necessary, you can reset the token pressing ``Reset OpenAPI Token``
```suggestion
If necessary, you can reset the token by pressing ``[Reset OpenAPI Token]`` button
```

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +* Click menu ``File >> Import URL``
:+1:

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +  * **Password** -- set **OpenAPI Token** (described `here <#authentication>`__)
```suggestion
  * **Password** -- set **OpenAPI Token** (how to get one is described in `authentication <#authentication>`__ above)
```

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +  If you're using Nginx you can add a setting like this::
```suggestion
  Alternatively, you can grant CORS headers in your web server. Below is example for Nginx::
```

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +This is how it is usually done from the odoo model:
```suggestion
This is how it is usually done from python code:
```

2020-04-28 13:43 UTC, yelizariev commented on openapi/doc/index.rst
> +Using API:
```suggestion
On using API it would be as following:
```

2020-04-28 13:43 UTC, yelizariev commented
Добавил стилистические замечания

2020-04-29 18:23 UTC, trojikman commented
> Добавил стилистические замечания

Применил через интерфейс твои правки, надо делать squash или так сойдет?

2020-05-01 12:13 UTC, yelizariev commented
Сойдет

2020-05-06 21:06 UTC, trojikman commented
I approve to merge it now

2020-05-06 21:06 UTC, merged