:shield: test if response is JSON serializable
itpp-labs/sync-addons pull request #148
Opened 2020-05-06 20:19 UTC by fedoranvar

2020-05-06 21:31 UTC, trojikman requested changes

2020-05-06 21:31 UTC, trojikman commented on openapi/tests/test_api.py
> +@tagged("json")
В первый раз вижу, когда используют такой тег (json), он же не оказывает никакого эффекта, разве нет?

2020-05-06 21:31 UTC, trojikman commented on openapi/tests/test_api.py
> +class JSONtest(HttpCase):
Думаю будет лучше если добавлять новый метод с тестом в существующий класс (TestAPI).

2020-05-06 21:31 UTC, trojikman commented on openapi/tests/test_api.py
> +class JSONtest(HttpCase):
Или в нем сложности с запуском?

2020-05-07 01:57 UTC, fedoranvar commented on openapi/tests/test_api.py
> +@tagged("json")
Тэгирование нужно было для того, чтобы запускать только этот тест (для дебага)

2020-05-07 01:57 UTC, fedoranvar commented on openapi/tests/test_api.py
> +class JSONtest(HttpCase):
Сложностей нет.

Исправил

2020-05-07 02:45 UTC, yelizariev reviewed
Что-то тест совсем под код и под решение подстроен. Мы в будущем можем рефакторинг сделать и тест придется переделывать. Лучше что-нибудь ближе к реальности. Например, запрос на чтение данных с полями даты.

2020-05-11 11:53 UTC, yelizariev commented on openapi/tests/test_api.py
> +    def test_correct_work(self):
Сделай нормальное имя. Тут все тесты проверяют что модуль нормально работает

2020-05-11 11:53 UTC, yelizariev commented on openapi/tests/test_api.py
> +        self.assertFalse(has_error)
assertIn("error", resp.json())

2020-05-11 14:31 UTC, fedoranvar commented on openapi/tests/test_api.py
> +    def test_correct_work(self):
test_response_has_no_error

2020-05-11 14:32 UTC, fedoranvar commented on openapi/tests/test_api.py
> +        self.assertFalse(has_error)
check

2020-05-11 15:10 UTC, trojikman approved these changes

2020-05-11 15:16 UTC, trojikman commented
I approve to merge it now

2020-05-11 15:17 UTC, merged