:zap: Added handling of json-request's parameter 'method_context' in …
itpp-labs/sync-addons pull request #155
Opened 2020-05-27 08:26 UTC by fedoranvar

…PATCH-method

2020-05-27 08:33 UTC, yelizariev commented
Надо бы еще пример в спецификации обновить 

https://github.com/itpp-labs/sync-addons/issues/154

2020-05-27 14:30 UTC, yelizariev reviewed
Нормально, но лучше параметр назвать просто context

2020-05-28 07:07 UTC, yelizariev commented on openapi/controllers/apijsonrequest.py
> +        self.context = dict(self.session.context)
Я не понял зачем поп надо удалять

2020-05-28 07:09 UTC, fedoranvar commented on openapi/controllers/apijsonrequest.py
> +        self.context = dict(self.session.context)
Потому, что функция pop выбиывает из self.params элемент с ключом context, а это значит, что в дальнейшем (и при обработке метода PATCH) этого элемента не будет

2020-05-28 07:41 UTC, yelizariev requested changes

2020-05-28 07:41 UTC, yelizariev commented on openapi/models/openapi_access.py
> +                            "context": {},
По итогу обсуждения, выяснилось что достаточно этой строчки

2020-05-28 07:47 UTC, yelizariev commented on openapi/controllers/apijsonrequest.py
> +        self.context = dict(self.session.context)
Обсудили в телеграме

2020-05-28 07:55 UTC, yelizariev approved these changes

2020-05-28 20:06 UTC, trojikman commented
I approve to merge it now

2020-05-28 20:07 UTC, merged