:book: add information about filling in the fields
itpp-labs/sync-addons pull request #158
Opened 2020-07-15 16:32 UTC by trojikman

2020-07-16 09:18 UTC, yelizariev requested changes

2020-07-16 09:18 UTC, yelizariev commented on openapi/doc/index.rst
> +Fill in field in existing record
```suggestion
Updating existing record
```

2020-07-16 09:18 UTC, yelizariev commented on openapi/doc/index.rst
> +We can do so using PUT method like this:
```suggestion
For example, to set *phone* value for a partner, make a PUT request in the following way:
```

2020-07-16 09:18 UTC, yelizariev commented on openapi/doc/index.rst
> +Or if you need to fill in many2one field you can do so:
```suggestion
To set many2one field, you need to pass id as a value:
```

2020-07-16 09:18 UTC, yelizariev commented on openapi/doc/index.rst
> +  -d '{ "title": *RECORD_ID*}' "http://example.com/api/v1/demo/res.partner/41"
титл это не many2one поле. Сделай company_id или parent_id

2020-07-19 19:42 UTC, trojikman commented
I approve to merge it now

2020-07-19 19:42 UTC, merged