[12.0] openapi: added CORS headers to response
itpp-labs/sync-addons pull request #165
Opened 2020-09-09 07:49 UTC by em230418

https://ru.wikipedia.org/wiki/Cross-origin_resource_sharing
Актульно как-минимум, когда разработчик делает гибридное (HTML+JS) мобильное приложение, тестирует на браузере, пытается использовать методы из OpenAPI и обламывается потому-что браузер запрещает.

2020-09-09 09:09 UTC, yelizariev requested changes
Надо как минимум сделать это настраиваемым

2020-09-09 09:09 UTC, yelizariev commented on openapi/controllers/pinguin.py
> +            ("Access-Control-Allow-Origin", "*"),
Эти ограничения не просто так сделаны. Просто так полный доступ не айс давать: я установил этот модуль на свою оду, злоумышленник выдал мне ссылку на сайт где джава скрипт от моего имени выкачает  всех ко клиентов или вообще отправит команду "отправить письмо всем клиентам от имени Ивана"

2020-09-09 09:10 UTC, yelizariev commented
Для разработки проще через энджинкс хедеры добавлять

2020-09-09 09:35 UTC, yelizariev commented on openapi/controllers/pinguin.py
> +            ("Access-Control-Allow-Origin", "*"),
Хотя, этот сценарий работает только если авторизация через куки, а здесь авторизация по хедерам

2020-09-09 09:43 UTC, yelizariev commented
Еще ведь метод OPTIONS есть, который оду не обрабатывает. Без него будет работать?

2020-09-09 09:46 UTC, em230418 commented on openapi/controllers/pinguin.py
> +            ("Access-Control-Allow-Origin", "*"),
Кстати, да. Чтобы авторизоваться, надо бы еще добавить https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers. Причем конкретно для Authorization там какие-то особые условия. 
Причем сценарий, который я описал, походу этот PR не решает.

Но клиент ставил задачу только это ставить.

2020-09-09 09:47 UTC, yelizariev commented
В общем, надо добавить комментарии почему это безопасно добавлять CORS хедеры.
Одновременно, надо добавить замечание, что для быстрой работы рекомендуется обрабатывать OPTIONS через внешний веб-сервер (например энджинкс)

2020-09-09 09:47 UTC, em230418 commented
> Еще ведь метод OPTIONS есть, который оду не обрабатывает. Без него будет работать?

Пока ждем ответа клиента. Я перестал понимать, где клиент хочет применить исправленый openapi.

2020-09-09 09:49 UTC, yelizariev commented
@trojikman если ПР примем, надо еще подправить в документации про свагер-редактор, что CORS будет работать и не нужно доп настроек делать

2020-10-31 07:34 UTC, yelizariev commented
> Еще ведь метод OPTIONS есть, который оду не обрабатывает. Без него будет работать?

Обрабатывает https://github.com/odoo/odoo/blob/c691f971325c21aca47eb597a0fda248a621dc7e/odoo/http.py

2020-11-06 04:30 UTC, trojikman commented
> Для разработки проще через энджинкс хедеры добавлять

Чтобы через nginx работало (по крайней мере в сваггере) - нужно ставить доп модуль, не очень бы хотелось просить в доках об этом.
P.S это лично с Иваном обсуждали

2021-05-27 08:49 UTC, trojikman commented
Пришли к какому то рабочему решению
https://github.com/itpp-labs/sync-addons/commit/bdeadfa92310e1656ffc44a51d2506bba8301dee#diff-2d676fe19cda0e5804065c49908b2efddee7e9292fc98073010f7977f80272a3
https://github.com/itpp-labs/sync-addons/commit/8913689f87ae6cbf398dff7dfd214625507a8bc2#diff-2d676fe19cda0e5804065c49908b2efddee7e9292fc98073010f7977f80272a3

2021-05-27 08:49 UTC, closed without merging