11.0 sync port
itpp-labs/sync-addons pull request #167
Opened 2020-09-15 12:44 UTC by trojikman

2020-09-27 14:10 UTC, yelizariev requested changes

2020-09-27 14:10 UTC, yelizariev commented on sync/models/sync_trigger_cron.py
> +    def create(self, vals):
Always use ``@api.model`` for create method

https://odoo-source.com/?q=def%20create%5C(self%2C%20vals%5C)&i=nope&files=&excludeFiles=po%24%7Cpot%24%7Cyml%24%7Cyaml%24%7Ccss%24%7C%2Fstatic%2Flib%2F&repos=13.0

2020-09-27 14:10 UTC, yelizariev commented on sync/models/sync_trigger_mixin.py
> +    def create(self, vals):
``@api.model``

2020-09-27 14:10 UTC, yelizariev commented on sync/models/sync_trigger_mixin.py
> +    def create(self, vals):
``@api.model``

2020-09-30 04:50 UTC, trojikman commented
I approve to merge it now

2020-09-30 04:50 UTC, merged