:zap: a new type of parameters for cases when we need the possibility…
itpp-labs/sync-addons pull request #249
Opened 2021-05-20 08:12 UTC by trojikman

… to translate the passed text

2021-05-20 09:23 UTC, yelizariev requested changes
визард экспорта еще обновить надо

2021-05-20 09:23 UTC, yelizariev commented on sync/doc/changelog.rst
> +**Improvement:** add a new type of parameters especially for cases when we need the possibility to translate text in the passed parameter
Translation + multiline. Вообще говоря, переводы уже были. Лучше написать что мы отделили переводимые от не переводимых, плюс бонусом мультилинии добавили в переводимые

2021-05-20 09:23 UTC, yelizariev commented on sync/models/sync_project.py
> +    value = fields.Char("Value")
Можно совсем удалить, т.к. в миксине это есть

2021-05-20 13:07 UTC, trojikman commented
Обновлю, когда #247 доделаем

2021-05-25 13:28 UTC, yelizariev reviewed
В eval context надо еще добавить переменную ``texts``

2021-05-25 13:28 UTC, yelizariev commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
Можно не пояснять. А название поменять на Text Values или что-нибудь другое придумать. 

Предыдущий раздел тоже желательно переименовать на Configs, правда будет расхождение с навзанием переменных.

Может просто назвать разделы Params, Texts, Secrets ?

2021-05-26 06:44 UTC, trojikman commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
А если Configs, Texts, Secrets

2021-05-26 08:45 UTC, yelizariev commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
Программисты запутаются разбираясь что params = Configs. Хотя, можно это обойти если оба названия поддерживать в коде. Если будешь делать, то обнови везде документацию на configs (+ напиши, что params тоже работает, это старое название)

2021-05-26 08:46 UTC, yelizariev commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
Configs только нет слова. Надо в интерфейсе писать Configurations, а переменную делать configs

2021-05-26 08:48 UTC, yelizariev commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
Правда у слова Configuration еще другое значение есть (конфигурация, структура), в отличие от Parameters.
Но вроде норм

2021-05-26 10:58 UTC, trojikman commented
> В eval context надо еще добавить переменную `texts`
В данный момент сделано вот так
![Screenshot from 2021-05-26 15-57-51](https://user-images.githubusercontent.com/23641186/119648658-294a1180-be3b-11eb-840b-6cb47b743b6d.png)

2021-05-26 11:11 UTC, trojikman commented on sync/views/sync_project_views.xml
> +                                <em>Text parameters which values can be translated</em>
Давай тогда Params оставим, а? :laughing:

2021-05-26 13:10 UTC, yelizariev commented on sync/doc/changelog.rst
> +**Improvement:** translatable parameters are highlighted in a separate group
Это ты слово "выделены" так перевел? Ты не то значение перевел

https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9-%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9/%D0%B2%D1%8B%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D1%8C

Лучше вообще не пытаться напрямую перевести, а на английском что-то составить.

add translatable multi-line parameters and make original params non-translatable

2021-05-26 13:10 UTC, yelizariev commented on sync/doc/changelog.rst
> +`2.2.0`
Скорее 3.0.0 всё таки, так как с этим обновлением теряются переводы в существующих параметрах

2021-05-26 13:11 UTC, yelizariev commented
> > В eval context надо еще добавить переменную `texts`
> 
> В данный момент сделано вот так
> ![Screenshot from 2021-05-26 15-57-51](https://user-images.githubusercontent.com/23641186/119648658-294a1180-be3b-11eb-840b-6cb47b743b6d.png)

лучше добавить новую переменную. Иначе можно создать параметр и текст с одинаковым именем и они перезапишутся

2021-05-31 10:01 UTC, trojikman commented on sync/doc/changelog.rst
> +**Improvement:** add a new type of parameters especially for cases when we need the possibility to translate text in the passed parameter
Про мультилинии не совсем понял

2021-05-31 11:27 UTC, yelizariev commented
sync/doc/index.rst еще обновить

2021-05-31 12:21 UTC, trojikman commented
Не уверен надо ли менять версию в модуле sync_telegram?

2021-05-31 14:30 UTC, yelizariev commented
> Не уверен надо ли менять версию в модуле sync_telegram?

Надо. Тоже Major update. 3.0.0

2021-05-31 15:41 UTC, yelizariev requested changes

2021-05-31 15:41 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
>          <field name="key">PARTNER_NAME_PREFIX</field>
в коде не поменял params.PARTNER_NAME_PREFIX на texts...

2021-05-31 15:41 UTC, yelizariev commented on sync_telegram/data/sync_project_data.xml
> +    <record id="telegram_project_param_message_sent" model="sync.project.text">
Может удалить раз не используется?

2021-05-31 15:41 UTC, yelizariev commented on sync/doc/changelog.rst
> +**Improvement:** add the possibility to fully duplicate the project
Заведи дело или пришей к существующему для переноса в ранние версии

2021-05-31 15:57 UTC, trojikman commented on sync/doc/changelog.rst
> +**Improvement:** add the possibility to fully duplicate the project
https://github.com/itpp-labs/sync-addons/issues/248

2021-06-01 09:37 UTC, yelizariev approved these changes

2021-06-01 11:26 UTC, merged