:zap: sync_telegram: allow editing telegram chat
itpp-labs/sync-addons pull request #258
Opened 2021-05-24 13:57 UTC by yelizariev

2021-05-25 13:03 UTC, trojikman commented
@yelizariev То что тут паблик юзер подписан автоматом это же норм?
![Screenshot from 2021-05-25 18-03-22](https://user-images.githubusercontent.com/23641186/119502586-84203200-bd83-11eb-8763-6ef2ba21b8ee.png)

2021-05-25 13:17 UTC, yelizariev commented
Я пока не понял. Вроде не должно быть. Но это не связано с моим ПР)

2021-05-25 13:19 UTC, yelizariev commented
@mentalko есть идеи?

2021-05-25 15:56 UTC, trojikman requested changes
Добавил Марка в подписчики, отправил от него сообщение - оно не дошло до телеги. От Митчела отправляются
![Screenshot from 2021-05-25 20-55-35](https://user-images.githubusercontent.com/23641186/119529522-9efea080-bd9b-11eb-91a3-e7b1497224d4.png)

2021-05-25 16:03 UTC, yelizariev commented
Этот тоже не связано с моим ПР, но это здесь исправлять надо

https://github.com/itpp-labs/sync-addons/blob/08944328bff5564826804da5668cc5fbf5947acc/sync_telegram/data/mail_sync_project_data.xml#L29

Надо всё проверку заменить на "сообщение не от телеграм пользователя"

@mentalko

2021-05-25 16:05 UTC, yelizariev commented
Что-нибудь типа 
```
if not mail_message.author_id.search_link(....)
```

2021-06-06 06:54 UTC, yelizariev commented
@trojikman может про демо отдельно ПР сделаешь и вольешь? Иначе конфликты возникнут с ПР https://github.com/itpp-labs/sync-addons/pull/265

2021-06-07 16:15 UTC, trojikman commented
> @trojikman может про демо отдельно ПР сделаешь и вольешь? Иначе конфликты возникнут с ПР #265

Done https://github.com/itpp-labs/sync-addons/pull/267

2021-06-09 10:29 UTC, yelizariev commented
@trojikman как будем готовы вливать, сделай ребейз

2021-06-13 16:16 UTC, trojikman commented
> Добавил Марка в подписчики, отправил от него сообщение - оно не дошло до телеги. От Митчела отправляются
> ![Screenshot from 2021-05-25 20-55-35](https://user-images.githubusercontent.com/23641186/119529522-9efea080-bd9b-11eb-91a3-e7b1497224d4.png)

Это всё ещё так

2021-06-13 16:29 UTC, trojikman approved these changes

2021-06-13 16:30 UTC, merged