:heart_eyes: remove link if record doesn't exist
itpp-labs/sync-addons pull request #286
Opened 2021-07-06 14:18 UTC by trojikman

2021-07-06 14:23 UTC, yelizariev commented
Add reference to the issue, please https://github.com/itpp-labs/sync-addons/issues/268

2021-07-06 14:31 UTC, trojikman commented
According to the tests something goes wrong

2021-07-06 14:36 UTC, yelizariev commented on sync/models/sync_link.py
> +        odoo_links = links.filtered(lambda r: r.system1 == ODOO)
```suggestion
        odoo_links = links.filtered(lambda r: r.system2 == ODOO)
```

?

2021-07-06 14:39 UTC, yelizariev commented on sync/models/sync_link.py
> +                "Delete obsolete links: {}".format(
Так ты не удаляешь, а исключаешь из результата

2021-07-06 14:39 UTC, yelizariev commented on sync/models/sync_link.py
> +        links = odoo_links
Если ссылок оду нет, то ты заменяешь на пустой список

2021-07-06 14:40 UTC, yelizariev commented on sync/models/sync_link.py
> +        links = odoo_links
```suggestion
        links = links - odoo_links_to_delete
```

2021-07-06 14:45 UTC, trojikman commented on sync/models/sync_link.py
> +                "Delete obsolete links: {}".format(
Стоит линки тоже удалять?

2021-07-06 15:07 UTC, yelizariev commented on sync/models/sync_link.py
> +                "Delete obsolete links: {}".format(
да

2021-07-06 15:10 UTC, yelizariev commented on sync/models/sync_link.py
> +        odoo_links_to_delete = odoo_links - odoo_links.exists()
odoo_links всегда существуют. Надо link.odoo проверять. В деле неправильно я написал https://github.com/itpp-labs/sync-addons/issues/268#issue-914438516

2021-07-07 13:49 UTC, yelizariev commented on sync/models/sync_link.py
> +                lambda r: r.ref2 in odoo_ids_to_remove
```suggestion
                lambda r: int(r.ref2) in odoo_ids_to_remove
```

2021-07-07 13:52 UTC, yelizariev commented on sync/models/sync_link.py
> +            )
```suggestion
            existing_odoo_records = self.env[model].sudo().browse(odoo_ids).exists()
            odoo_ids_to_remove = set(odoo_ids) - set(existing_odoo_records.ids)
            odoo_links_to_delete = odoo_links.filtered(
                lambda r: int(r.ref2) in odoo_ids_to_remove
            )
```

2021-07-08 14:37 UTC, yelizariev requested changes
Лучше архивировать, а не удалять. Во-первых, можно лишнего удалить, во-вторых легче будет анализировать что произошло (логи есть, но там сложнее искать)

2021-07-08 14:37 UTC, yelizariev commented on sync/models/sync_link.py
> +                "Delete obsolete links: {}".format(
Это сообщение будет всегда печататься, даже если ничего не удаляем

2021-07-11 13:14 UTC, trojikman commented
надо изменить подход, потому что эти изменения проблему не решают

2024-08-19 11:08 UTC, closed without merging