14.0 sync viber
itpp-labs/sync-addons pull request #287
Opened 2021-07-07 17:49 UTC by yelizariev

2021-07-07 18:19 UTC, yelizariev commented
- [ ] finish refactoring (test sync_telegram)
- [ ] implement viber in the same way as it's done for telegram (text messages)
- [ ] implement sending files to/from viber

2021-07-26 08:42 UTC, trojikman requested changes
<details>

![Screenshot from 2021-07-26 13-42-14](https://user-images.githubusercontent.com/23641186/126960318-c206d955-0a82-42d7-92a3-0076250f3438.png)

</details>
судя по всему конфликты при совместной работе с телеграмом

2021-07-27 12:54 UTC, trojikman commented
Заметил, когда отправляю такие ошибки из оду, то появляются такие ошибки:
![Screenshot from 2021-07-27 17-53-55](https://user-images.githubusercontent.com/23641186/127156894-4585ca80-2a4a-477c-b762-588ce0d5e8fc.png)

2021-07-27 12:58 UTC, trojikman commented
При попытке в телегу написать вот такое выводит:

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 87, in <module>
  File "", line 33, in handle_webhook
  File "/mnt/addons/sync-addons/sync_telegram/models/sync_project.py", line 90, in create_mail_сhannel
    .mapped("name")
  File "<decorator-gen-139>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_channel.py", line 252, in create
    ).create(vals)
  File "<decorator-gen-135>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-129>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_alias_mixin.py", line 42, in create
    records = super(AliasMixin, self).create(valid_vals_list)
  File "<decorator-gen-69>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3940, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2402, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2414, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for mail.channel.channel_type: 'telegram'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 135, in run
    result = self._eval(code, function, args, kwargs, eval_context)
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 165, in _eval
    code, eval_context, mode="exec", nocopy=True
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'ValueError'>: "Wrong value for mail.channel.channel_type: 'telegram'" while evaluating
'\ndef handle_webhook(httprequest):\n  data = json.loads(httprequest.data.decode("utf-8"))\n  log("Raw data: %s" % data, LOG_DEBUG)\n\n  update = telegram.parse_data(data)\n  message = update.message or update.edited_message\n  odoo_message_text = message.text or message.caption or ""\n  name = params.PARTNER_NAME_TEMPLATE % user2name(message.from_user)\n  record_name = params.CHAT_RECORD_NAME_TEMPLATE % user2name(message.from_user)\n  telegram_user_ref =  message.from_user.id\n  main_operator = env.user.browse(operators_user_list[0])\n\n  partner_link = get_link(TG_PARTNER_REL, telegram_user_ref)\n\n  if not partner_link:\n    partner_image =  telegram.getUserPhoto(telegram_user_ref)\n    partner = env["res.partner"].with_user(main_operator).create({"name": name, "image_1920": partner_image})\n    partner.set_link(TG_PARTNER_REL, telegram_user_ref, sync_date=None, allow_many2many=False)\n    partner_link = get_link(TG_PARTNER_REL, telegram_user_ref)\n\n  if params.WEBHOOK_CHAT != "no":\n    if message.text == "/start":\n      telegram.sendMessage(telegram_user_ref, texts.TELEGRAM_WELCOME_MESSAGE)\n    elif bool(update.edited_message):\n      odoo_message_text = "Contact has edited the message:"\n\n    channel_link = get_link(TG_CHAT_CHANNEL_REL, telegram_user_ref)\n    if channel_link:\n      channel = channel_link.odoo\n    else:\n      partners = [partner_link.odoo.id] + operators_partner_list\n      channel = telegram.create_mail_сhannel(partners)\n      channel.set_link(TG_CHAT_CHANNEL_REL, telegram_user_ref)\n\n    model_rel = TG_CHAT_MODEL_REL + params.CHAT_MODEL\n    if params.CHAT_MODEL != "res.partner":\n      record_model_link = get_link(model_rel, telegram_user_ref)\n\n      if not record_model_link:\n        record_model = env[params.CHAT_MODEL].with_user(main_operator).create({"name": record_name, "partner_id": partner_link.odoo.id})\n        record_model.set_link(model_rel, telegram_user_ref, sync_date=None, allow_many2many=False)\n\n        record_model.message_post(body="""<b><a href="/web#action=%s&active_id=mail.channel_%s">Chat with partner is created. </a></b>""" %\n        (env.ref("mail.action_discuss").id, channel.id), author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n\n        channel.message_post(body="""<b><a href="/web#id=%s&model=%s">Record is created. </a></b>""" %\n        (record_model.id, record_model._name), author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n\n    file_bin_data = []\n    telegram_document = update.message.document\n    telegram_photo = update.message.photo\n    telegram_media = update.message.video or update.message.voice or update.message.video_note\n    telegram_sticker = update.message.sticker\n\n\n    if not update.message.text:\n        if telegram_photo and telegram_photo[-1].file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_photo: %s" % telegram_photo, LOG_INFO)\n            file_bin_data = telegram.getMediaFile(telegram_user_ref, telegram_photo[-1])\n\n        elif telegram_media and telegram_media.file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_media: %s" % telegram_media, LOG_INFO)\n            file_bin_data = telegram.getMediaFile(telegram_user_ref, telegram_media)\n\n        elif telegram_document and telegram_document.file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_document: %s" % telegram_document, LOG_INFO)\n            file_bin_data = telegram.getDocumentFile(telegram_user_ref, telegram_document)\n\n        elif telegram_photo or telegram_media or telegram_document:\n            channel.message_post(body="Incoming file is too big and cannot be downloaded due to Telegram API restirctions",\n            author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n            telegram.sendMessage(telegram_user_ref, "File is too big, file size must not exceed 20 MB.")\n\n        if telegram_sticker:\n            log("telegram_sticker: %s" % telegram_sticker, LOG_INFO)\n            channel.message_post(body=telegram_sticker.emoji, author_id=partner_link.odoo.id,\n            message_type="comment", subtype_xmlid="mail.mt_comment")\n\n\n    channel.message_post(body=odoo_message_text, attachments=[file_bin_data], author_id=partner_link.odoo.id,\n    message_type="comment", subtype_xmlid="mail.mt_comment")\n\n\n\n        \nEXECUTION_RESULT_ = handle_webhook(*EXECUTION_ARGS_, **EXECUTION_KWARGS_)\n        
```

</details>

2021-07-27 15:22 UTC, trojikman commented
Такую ошибку наблюдаю сейчас в логах:
![Screenshot from 2021-07-27 20-21-33](https://user-images.githubusercontent.com/23641186/127181246-6d5b6acc-5836-4b23-b9fa-5c722f0556c1.png)

2021-07-27 15:28 UTC, trojikman commented
С телеграмом снова не заработало:

<details>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 87, in <module>
  File "", line 33, in handle_webhook
  File "/mnt/addons/sync-addons/sync_telegram/models/sync_project.py", line 90, in create_mail_сhannel
    .mapped("name")
  File "<decorator-gen-139>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 323, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_channel.py", line 252, in create
    ).create(vals)
  File "<decorator-gen-135>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-129>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_alias_mixin.py", line 42, in create
    records = super(AliasMixin, self).create(valid_vals_list)
  File "<decorator-gen-68>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3868, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3940, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2402, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2414, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for mail.channel.channel_type: 'telegram'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 135, in run
    result = self._eval(code, function, args, kwargs, eval_context)
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 165, in _eval
    code, eval_context, mode="exec", nocopy=True
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'ValueError'>: "Wrong value for mail.channel.channel_type: 'telegram'" while evaluating
'\ndef handle_webhook(httprequest):\n  data = json.loads(httprequest.data.decode("utf-8"))\n  log("Raw data: %s" % data, LOG_DEBUG)\n\n  update = telegram.parse_data(data)\n  message = update.message or update.edited_message\n  odoo_message_text = message.text or message.caption or ""\n  name = params.PARTNER_NAME_TEMPLATE % user2name(message.from_user)\n  record_name = params.CHAT_RECORD_NAME_TEMPLATE % user2name(message.from_user)\n  telegram_user_ref =  message.from_user.id\n  main_operator = env.user.browse(operators_user_list[0])\n\n  partner_link = get_link(TG_PARTNER_REL, telegram_user_ref)\n\n  if not partner_link:\n    partner_image =  telegram.getUserPhoto(telegram_user_ref)\n    partner = env["res.partner"].with_user(main_operator).create({"name": name, "image_1920": partner_image})\n    partner.set_link(TG_PARTNER_REL, telegram_user_ref, sync_date=None, allow_many2many=False)\n    partner_link = get_link(TG_PARTNER_REL, telegram_user_ref)\n\n  if params.WEBHOOK_CHAT != "no":\n    if message.text == "/start":\n      telegram.sendMessage(telegram_user_ref, texts.TELEGRAM_WELCOME_MESSAGE)\n    elif bool(update.edited_message):\n      odoo_message_text = "Contact has edited the message:"\n\n    channel_link = get_link(TG_CHAT_CHANNEL_REL, telegram_user_ref)\n    if channel_link:\n      channel = channel_link.odoo\n    else:\n      partners = [partner_link.odoo.id] + operators_partner_list\n      channel = telegram.create_mail_сhannel(partners)\n      channel.set_link(TG_CHAT_CHANNEL_REL, telegram_user_ref)\n\n    model_rel = TG_CHAT_MODEL_REL + params.CHAT_MODEL\n    if params.CHAT_MODEL != "res.partner":\n      record_model_link = get_link(model_rel, telegram_user_ref)\n\n      if not record_model_link:\n        record_model = env[params.CHAT_MODEL].with_user(main_operator).create({"name": record_name, "partner_id": partner_link.odoo.id})\n        record_model.set_link(model_rel, telegram_user_ref, sync_date=None, allow_many2many=False)\n\n        record_model.message_post(body="""<b><a href="/web#action=%s&active_id=mail.channel_%s">Chat with partner is created. </a></b>""" %\n        (env.ref("mail.action_discuss").id, channel.id), author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n\n        channel.message_post(body="""<b><a href="/web#id=%s&model=%s">Record is created. </a></b>""" %\n        (record_model.id, record_model._name), author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n\n    file_bin_data = []\n    telegram_document = update.message.document\n    telegram_photo = update.message.photo\n    telegram_media = update.message.video or update.message.voice or update.message.video_note\n    telegram_sticker = update.message.sticker\n\n\n    if not update.message.text:\n        if telegram_photo and telegram_photo[-1].file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_photo: %s" % telegram_photo, LOG_INFO)\n            file_bin_data = telegram.getMediaFile(telegram_user_ref, telegram_photo[-1])\n\n        elif telegram_media and telegram_media.file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_media: %s" % telegram_media, LOG_INFO)\n            file_bin_data = telegram.getMediaFile(telegram_user_ref, telegram_media)\n\n        elif telegram_document and telegram_document.file_size < telegram.MAX_SIZE_TO_DOWNLOAD:\n            log("telegram_document: %s" % telegram_document, LOG_INFO)\n            file_bin_data = telegram.getDocumentFile(telegram_user_ref, telegram_document)\n\n        elif telegram_photo or telegram_media or telegram_document:\n            channel.message_post(body="Incoming file is too big and cannot be downloaded due to Telegram API restirctions",\n            author_id=odoobot_id, message_type="comment", subtype_xmlid="mail.mt_comment")\n            telegram.sendMessage(telegram_user_ref, "File is too big, file size must not exceed 20 MB.")\n\n        if telegram_sticker:\n            log("telegram_sticker: %s" % telegram_sticker, LOG_INFO)\n            channel.message_post(body=telegram_sticker.emoji, author_id=partner_link.odoo.id,\n            message_type="comment", subtype_xmlid="mail.mt_comment")\n\n\n    channel.message_post(body=odoo_message_text, attachments=[file_bin_data], author_id=partner_link.odoo.id,\n    message_type="comment", subtype_xmlid="mail.mt_comment")\n\n\n\n        \nEXECUTION_RESULT_ = handle_webhook(*EXECUTION_ARGS_, **EXECUTION_KWARGS_)\n    
```

</details>

2021-07-27 15:31 UTC, yelizariev commented
Да, две попытки в час есть чтобы запустить без багов)

> Такую ошибку наблюдаю сейчас в логах:
> ![Screenshot from 2021-07-27 20-21-33](https://user-images.githubusercontent.com/23641186/127181246-6d5b6acc-5836-4b23-b9fa-5c722f0556c1.png)
> 
> Видимо такое отображение связано с этой ошибкой:
> ![Screenshot from 2021-07-27 20-22-34](https://user-images.githubusercontent.com/23641186/127181473-b5378f1b-d57d-404e-bc09-fa8c5149bf64.png)
> 
> Такое было в прошлых запусках, но потом становилось нормальным, сейчас вот опять

2021-07-30 10:31 UTC, trojikman commented
<detais>

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 330, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 72, in <module>
  File "", line 63, in handle_webhook
AttributeError: 'wrap_module' object has no attribute 'ViberDeliveredRequest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 135, in run
    result = self._eval(code, function, args, kwargs, eval_context)
  File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 165, in _eval
    code, eval_context, mode="exec", nocopy=True
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 346, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'AttributeError'>: "'wrap_module' object has no attribute 'ViberDeliveredRequest'" while evaluating
'def handle_webhook(httprequest):\n  data = json.loads(httprequest.data.decode("utf-8"))\n  log("Raw data: %s" % data, LOG_DEBUG)\n\n  if not viber_webhook_check(httprequest):\n    return "no, thanks", 403\n\n  viber_user_ref, vrequest = viber_webhook_parse(httprequest)\n\n  if not viber_user_ref:\n    return\n\n  def partner_vals(viber_api, viber_user_ref):\n    try:\n        data = viber_api.get_user_details(viber_user_ref)\n    except Exception as err:\n        return {\n          "name": "Viber user %s" % viber_user_ref,\n          "comment": str(err),\n        }\n    return {\n      "name": data["name"],\n      "lang": get_lang(env, data.get("language", "").replace("-", "_")).code,\n      "image_1920": url2base64(data.get("avatar")),\n      "comment": str(data),\n    }\n  partner_kwargs = dict(viber_api=viber_api, viber_user_ref=viber_user_ref)\n  partner, is_new_partner = multi_livechat.get_partner(VIBER_PARTNER, viber_user_ref, partner_vals, partner_kwargs)\n\n  if params.WEBHOOK_CHAT != "no":\n    channel_name = partner.name\n    operators_user_ids = list(map(int, params.OPERATOR_IDS.split(",")))\n    operators_partner_ids = env.user.browse(operators_user_ids).mapped("partner_id").ids\n    partner_ids = [partner.id] + operators_partner_ids\n    channel, is_new_channel = multi_livechat.get_channel(VIBER_CHANNEL, viber_user_ref, channel_name, partner_ids)\n\n    if params.CHAT_MODEL != "res.partner":\n      def thread_vals(partner):\n        return {\n          "name": partner.name,\n        }\n      thread_kwargs = dict(partner=partner)\n      record_message = """<b><a href="channel_url">Chat with partner is created.</a></b>""".format(\n        channel_url=multi_livechat.get_channel_url(channel)\n      )\n      thread, is_new_thread = multi_livechat.get_thread(\n        "%s:%s" % (VIBER_THREAD, params.CHAT_MODEL),\n        viber_user_ref,\n        thread_vals,\n        thread_kwargs,\n        params.CHAT_MODEL,\n        record_message,\n      )\n      if is_new_thread:\n        multi_livechat.post_channel_message(channel,\n        """<b><a href="{record_url}">Record is created. </a></b>""".format(\n          record_url=multi_livechat.get_record_url(thread)\n          ))\n\n    odoo_message_text = None\n    if isinstance(vrequest, viber_requests.ViberMessageRequest):\n      odoo_message_text = vrequest.message.text\n    elif isinstance(vrequest, viber_requests.ViberDeliveredRequest):\n      # TODO\n      pass\n    else:\n      odoo_message_text = str(data)\n    log("type=%s" % type2str(vrequest))\n    # TODO files processing\n    multi_livechat.post_channel_message(channel, odoo_message_text)\n\nEXECUTION_RESULT_ = handle_webhook(*EXECUTION_ARGS_, **EXECUTION_KWARGS_)\n    
```

</details>

2021-08-02 11:15 UTC, trojikman commented
Лишняя инфа чот попадает как будто:
![Screenshot from 2021-08-02 16-14-28](https://user-images.githubusercontent.com/23641186/127853169-08aa2512-609e-4d6d-be12-131141801745.png)

2021-08-03 06:42 UTC, trojikman commented
Теперь шлёт None сам
![Screenshot from 2021-08-03 11-42-11](https://user-images.githubusercontent.com/23641186/127969804-94294511-ecc9-49ab-83ab-ccc6f9a2dbc3.png)

2021-08-03 08:24 UTC, trojikman approved these changes
Проверил работу отдельно и вместе с телеграмом

2021-08-03 20:52 UTC, trojikman requested changes
Не понял связано это или нет. В вайбере решил добавить аватар и посомтреть как работает его загрузка в оду. После этого начало вот так возвращать сообщения:
![Screenshot from 2021-08-04 01-50-01](https://user-images.githubusercontent.com/23641186/128084481-32732b7d-cf30-4fc8-8357-78ea49378520.png)

2021-08-03 20:52 UTC, trojikman commented on multi_livechat/__manifest__.py
> +    "website": "https://github.com/itpp-labs/sync-addons",
Ссылку точно эту оставлять? Вроде бы и не sync_* модуль, чтобы на базовый модуль sync в магазине ссылку оставлять, согласно правилам. Может эту  https://twitter.com/OdooFree ?

2021-08-03 20:52 UTC, trojikman commented on multi_livechat/models/mail_channel.py
> +        # domain += [('id', 'in', pinned_channels.ids)]
Обязательно оставлять закомменченные строки? Может туду хотя бы добавить зачем это нужно?

2021-08-03 20:52 UTC, trojikman commented on sync/tools.py
> +class LogExternalQuery(object):
Может докстринг к этому классу добавить, где немного раскрыть зачем это нужно, как использоваь и тд? Или в index.rst

2021-08-04 10:37 UTC, yelizariev commented on multi_livechat/__manifest__.py
> +    "website": "https://github.com/itpp-labs/sync-addons",
Модуль планируется использовать только с sync_*, так что не строго по правилам сделал

2021-08-06 06:28 UTC, trojikman commented
Сейчас файл можно отправить и не будет уведомления о том, что файл не отправляется в вайбер, норм так пока?

2021-08-06 07:08 UTC, yelizariev commented
Клиентов предупредить и норм

2021-08-06 07:12 UTC, trojikman approved these changes
it works!

2021-08-06 07:12 UTC, merged

2021-08-06 07:14 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/06/21 - 08/06/21
Work session total: 1:01:51
Billable: Yes

Grand total: 1:01:51

2021-08-07 04:01 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/06/21 - 08/06/21
Work session total: 1:36:52
Billable: Yes

Grand total: 2:38:43