sync: finish porting to v13
itpp-labs/sync-addons pull request #291
Opened 2021-07-10 14:17 UTC by mentalko

какой смайлик в комит добавить?

2021-07-10 16:12 UTC, yelizariev commented
:ambulance:

2021-07-10 16:12 UTC, yelizariev commented
Обнови описание комита https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2021-07-10 16:14 UTC, yelizariev requested changes

2021-07-10 16:14 UTC, yelizariev commented on sync/views/sync_trigger_automation_views.xml
>                  <div class="oe_button_box" name="button_box">
TODO

2021-07-12 10:13 UTC, yelizariev commented
#257 это не то дело

2021-07-12 10:13 UTC, yelizariev commented
#215 должно быть

2021-07-12 10:27 UTC, mentalko commented
pre-commit забыл

2021-07-12 10:42 UTC, mentalko commented
хм ругается, почему?

2021-07-12 11:58 UTC, yelizariev requested changes
update version and changelog

2021-07-13 09:53 UTC, mentalko commented
хотел еще в этот ПР добавить решение этой проблемы, чтоб один номер версии был https://github.com/itpp-labs/sync-addons/issues/242

2021-07-16 06:27 UTC, mentalko commented
получается в этот ПР еще можно добавить решение #242.... но так как там проблема в том что изменения были затерты, значит надо завести новое дело и уже в комите его номер указывать

2021-07-16 07:19 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Fix:** set a correct name for run triger button
> - **Fix:** set a correct name for run triger button

Пользователю не интересно знать про какие-то названия в коде. Надо написать какая проблема решается, а как решается это вторично

2021-07-17 15:34 UTC, mentalko commented on sync/doc/changelog.rst
> +- **Fix:** set a correct name for run triger button
Fix: it was impossible to run manual trigger on task form

2021-07-18 19:07 UTC, yelizariev commented
I approve to merge it now

2021-07-18 19:08 UTC, yelizariev commented
I approve to merge it now

2021-07-18 19:08 UTC, merged