14.0 dont export values
itpp-labs/sync-addons pull request #302
Opened 2021-07-20 12:22 UTC by mentalko

2021-07-20 12:33 UTC, mentalko commented
Где здесь передается (хранится) name.xml ?

```
   data = etree.tostring(
            root,
            xml_declaration=True,
            encoding="UTF-8",
            pretty_print=True,
            doctype=copyright_str,
        )
        data = base64.encodebytes(data)
        self.write({"state": "get", "data": data})
        return self.get_wizard()
```

2021-07-20 13:22 UTC, yelizariev commented
get_wizard формирует словарь, который веб-клиент использует чтобы открыть визард

2021-07-20 13:26 UTC, yelizariev commented
> Где здесь передается (хранится) name.xml ?
> Сама переменная рассчитывается в начале кода, а вот где она передается в название файла при сохранении?

https://github.com/itpp-labs/sync-addons/blob/7fb862a58c9977321f0c19c7d344c6f8fa133f16/sync/wizard/sync_make_module_views.xml#L22

2021-07-29 11:29 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Improvement:** default values do not overwrite the current "Sync Projects" values after re-importing the XML data files.
```suggestion
- **Improvement:** default values do not overwrite the current "Sync Projects" values after module updating.
```

2021-07-29 11:29 UTC, yelizariev commented on sync/__manifest__.py
> +    "version": "14.0.4.0.2",
```suggestion
    "version": "14.0.4.1.0",
```

2021-07-29 11:31 UTC, yelizariev commented on sync/tests/test_default_value.py
> +# https://github.com/itpp-labs/sync-addons/blob/e924974e60ba40fbc7b700a96b1d95b9932e3640/base_api/tests/test_base.py
![delete](https://user-images.githubusercontent.com/186131/127484721-2569c356-a703-4466-9b43-ba93a4bff144.jpg)

2021-07-29 11:31 UTC, yelizariev commented on sync/tests/test_default_value.py
> +# Copyright 2020 Ivan Yelizariev <https://twitter.com/yelizariev>
not true

2021-07-30 07:27 UTC, yelizariev reviewed
:+1: 

Добавь свой копирайт во все изменяемые файлы (кроме файлов документации)

2021-07-30 07:27 UTC, yelizariev commented on sync/tests/test_default_value.py
> +@tagged("post_install", "-at_install")
Удали и будут значения по умолчанию использоваться

2021-07-30 07:27 UTC, yelizariev commented on sync/tests/test_default_value.py
> +        self.assertNotEqual(test_record.value, t_value)
```suggestion
        self.assertEqual(test_record.value, t_new_value)
```

2021-07-30 07:27 UTC, yelizariev commented on sync/wizard/sync_make_module.py
> +                )
Про это тоже напиши в changelog (текстовые параметры не экспортировались)

2021-07-30 07:27 UTC, yelizariev commented on sync/models/sync_project.py
> +    default_value = fields.Char(inverse="_inverse_default_value")
добавь help= и напиши как работает это поле

2021-08-01 08:44 UTC, mentalko reviewed
не знаю как открыл review и как его закрыть

2021-08-01 11:07 UTC, yelizariev requested changes

2021-08-01 11:07 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Improvement:** default values do not overwrite the current "Sync Projects" values after module updating.
Непонятно написано: "Sync Projects" values

2021-08-01 11:07 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Fix:** added export of text parameter values
```suggestion
- **Fix:** add exporting of text parameter values
```

2021-08-01 11:07 UTC, yelizariev commented on sync/models/sync_project.py
> +        inverse="_inverse_default_value",
Я вспомнил, что префикс default_ зарезервирован. Лучше переименуй на initial_value

2021-08-01 11:07 UTC, yelizariev commented on sync/models/sync_project.py
> +        help="It's used during module upgrade to prevent overwriting parameter values.",
Написано что предотвращает, не написано каким образом, как использовать

2021-08-01 11:07 UTC, yelizariev commented on sync/tests/test_default_value.py
> +        t_new_value = "New value"
Можно префикс t_ убрать

2021-08-01 11:07 UTC, yelizariev commented on sync/tests/test_default_value.py
> +        self.assertEqual(test_record.value, t_new_value)
тесты норм. Комментарии только по разному написано
1 существительно + существительное
2. глагол + существительное
3. нет комментария =)

2021-08-01 11:07 UTC, yelizariev commented on sync/wizard/sync_make_module.py
> +                )
Можно в отдельный комит выделить, чтобы легче проверять и чери-пикать было

2021-08-10 09:54 UTC, mentalko commented
Ребейз сделан

2021-08-12 04:01 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/11/21 - 08/11/21
Work session total: 0:00:13
Billable: Yes

Grand total: 0:00:13

2021-08-13 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/12/21 - 08/12/21
Work session total: 0:11:52
Billable: Yes

Grand total: 0:12:05

2021-08-16 08:58 UTC, trojikman approved these changes

2021-08-16 08:58 UTC, trojikman commented
I approve to merge it now

2021-08-16 08:58 UTC, merged

2021-08-16 09:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/16/21 - 08/16/21
Work session total: 0:17:47
Billable: Yes

Grand total: 0:29:52

2021-08-17 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/16/21 - 08/16/21
Work session total: 0:12:13
Billable: Yes

Grand total: 0:42:05