14.0 multi livechat
itpp-labs/sync-addons pull request #321
Opened 2021-08-18 13:04 UTC by yelizariev

2021-08-20 08:54 UTC, trojikman requested changes

2021-08-20 08:54 UTC, trojikman commented on multi_livechat/doc/changelog.rst
> +- **New:** hide channel by clicking a [X] button
После того как делаю это выходит такая ошибка:
![Screenshot from 2021-08-20 13-52-21](https://user-images.githubusercontent.com/23641186/130207950-4f4f07b6-2b2c-456d-a96a-3a93f30a1281.png)

2021-08-20 13:40 UTC, yelizariev commented on multi_livechat/doc/changelog.rst
> +- **New:** hide channel by clicking a [X] button
У меня работает...
Может шаги поточнее есть?

2021-08-20 13:50 UTC, yelizariev commented on multi_livechat/doc/changelog.rst
> +- **New:** hide channel by clicking a [X] button
Или посмотри в браузере кто вызывает channel_pin метод. Я только одно место нашел и там аргумент uuid есть

2021-08-20 14:38 UTC, trojikman commented on multi_livechat/doc/changelog.rst
> +- **New:** hide channel by clicking a [X] button
неправльно написал: 
1) нажимаю на крестик после 
2) отправляю сообщение боту через телеграм
вот после этого вышла ошибка

2021-08-21 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 08/20/21 - 08/20/21
Work session total: 0:17:16
Billable: Yes

Grand total: 0:17:16

2021-08-24 12:09 UTC, trojikman approved these changes

2021-08-24 12:09 UTC, merged