14.0 change tg lib
itpp-labs/sync-addons pull request #326
Opened 2021-08-25 14:18 UTC by mentalko

2021-09-02 05:42 UTC, yelizariev commented on sync_telegram/doc/changelog.rst
> +- **Improvement:** moving to another telegram library
```suggestion
- **Improvement:** use another telegram library
```

2021-09-02 05:42 UTC, yelizariev commented on sync_telegram/models/sync_project.py
> +            "MAX_SIZE_TO_DOWNLOAD": MAX_SIZE_TO_DOWNLOAD,
Зачем убрал из словаря "телеграм"?

2021-09-02 05:42 UTC, yelizariev commented on sync_telegram/models/sync_project.py
> +            bot.set_webhook(*args, **kwargs)
Здесь тоже можно  декоратор применить

2021-09-02 05:42 UTC, yelizariev commented on sync_telegram/models/sync_project.py
> +            "Telegram->The user's photo has been added to the partner record.",
В этом параметре нужно дать название внешнему запросу. Не нужно предложение целое писать

2021-09-02 05:42 UTC, yelizariev commented on sync_telegram/data/sync_project_data.xml
> +TG_THREAD="TG_THREAD"
Так ты все существующие установки ломаешь. Лучше не ломать ссылки, если можно не ломать

2021-09-02 07:45 UTC, mentalko commented
тест ругается на pyTelegramBotAPI

2021-09-28 08:23 UTC, yelizariev requested changes

2021-09-28 08:23 UTC, yelizariev commented on requirements.txt
> +pyTelegramBotAPI
Демо проект в Sync Studio тоже придется переделать, т.к. имя пакета в питоне одинаковое

2021-09-30 10:33 UTC, yelizariev requested changes

2021-09-30 10:33 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
> -    user_ref = "%s@telegram" % message.from_user.id
А зачем ты меняешь эту часть?

2021-09-30 10:33 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
> +        log(str(partner), LOG_DEBUG)
Логи нужно понятные печатать или убрать. Как сейчас сделано будет прост партер печататься и нужно догадываться к чему это отностися

2021-09-30 10:33 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
> -
Я так понимаю в xml можно вообще ничего не менять -- не зависит от библиотеки. Если ты хочешь что-то еще изменить в демо проекте, то нужно обосновать и указать изменения в changelog.rst

2021-09-30 10:33 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Improvement:** use another telegram library in Telegram demo project
```suggestion
- **Improvement:** use light telegram library in Telegram demo project (pyTelegramBotAPI)
```

2021-09-30 10:33 UTC, yelizariev commented on sync/models/sync_project_demo.py
> -    _logger.debug(err)
Нужно сохранить трай блок. Он не просто так здесь. Иначе работать не будет пока телеграм библиотеку не установишь, которая далеко не всем нужна

2021-09-30 10:33 UTC, yelizariev commented on sync/models/sync_project_demo.py
> -            "html2plaintext": html2plaintext,
Обоснуй в описании комита

2021-09-30 12:46 UTC, mentalko commented on sync/models/sync_project_demo.py
> -            "html2plaintext": html2plaintext,
этот код из тулзов убрали вот и не нужен он теперь

2021-09-30 12:48 UTC, mentalko commented on sync/data/sync_project_telegram_demo.xml
> -
логичнее использовать преимущества линков

2021-09-30 12:48 UTC, mentalko commented on sync/data/sync_project_telegram_demo.xml
> -    user_ref = "%s@telegram" % message.from_user.id
логичнее использовать преимущества линков

2021-10-01 07:26 UTC, yelizariev commented on sync/models/sync_project_demo.py
> -            "html2plaintext": html2plaintext,
Да, но это нужно в описание комита добавить

2021-10-01 11:09 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
> -    user_ref = "%s@telegram" % message.from_user.id
Логичнее, но это демо, которое показывает другие стороны. Например, можно понять как модуль работает не погружаясь сразу в линки

2021-10-01 11:10 UTC, yelizariev requested changes

2021-10-01 11:10 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Improvement:** add an example of using links to the Telegram demo project
Не надо)
Ссылки много еще где можно посмотреть. Тут специально пример сделан без ссылок

2021-10-01 11:14 UTC, yelizariev commented on sync/doc/changelog.rst
> +- **Fix:** remove `html2plaintext` method from eval context
Это только запутает клиента. Ты написал "удаляем". А он не удаляется. Этот метод доступен к использованию. Он просто через глобально везде добавляется, не нужно в контекте проекта его еще раз добавлять. Удали эту строчку здесь. А в описании комита напиши почему удалил код

2021-10-04 06:19 UTC, yelizariev approved these changes
Ну вроде норм, если работает

2021-10-04 06:19 UTC, yelizariev commented on sync/data/sync_project_telegram_demo.xml
> -
Может не будешь пустые строчки удалять?

2021-10-04 06:19 UTC, yelizariev commented on sync_telegram/doc/changelog.rst
> +- **Improvement:** code refactoring
Про рефакторинг в описании комита еще укажи

2021-10-06 11:05 UTC, yelizariev approved these changes

2022-07-18 12:55 UTC, closed without merging