:ambulance: sync: delete base.automation on deleting sync.task
itpp-labs/sync-addons pull request #333
Opened 2021-09-09 04:23 UTC by yelizariev

2021-09-09 12:57 UTC, trojikman commented
Ошибку не воспроизвёл. Проверял на базе sync_telegram:
1) Удалил таск который отвечает за получение сообщений из Телеграма
2) Отправил сообщение боту в телеграме, 
3) Сообщение не отобразилось в Оду, в логах появилась запись типа `POST /website/action-json/b56a25a4-789b-49d4-bed4-caf03043f091 HTTP/1.0" 200`, описанной ошибки нет

2021-09-09 13:26 UTC, trojikman reviewed
Ошибку не воспроизвёл. Проверял на базе sync_telegram:
1) Удалил таск который отвечает за получение сообщений из Телеграма
2) Отправил сообщение боту в телеграме, 
3) Сообщение не отобразилось в Оду, в логах появилась запись типа `POST /website/action-json/b56a25a4-789b-49d4-bed4-caf03043f091 HTTP/1.0" 200`, описанной ошибки нет

Сам db trigger похоже удалился: 
![Screenshot from 2021-09-09 17-59-11](https://user-images.githubusercontent.com/23641186/132690263-c7a49979-b194-486f-8fcf-f0b408589ed8.png)
Хотя, я не лез смотреть, как они отображаются в этой форме

2021-09-09 17:25 UTC, trojikman approved these changes
Воспроизвёл, решение предотварщает удаление таска до тех пор пока сам триггер не будет удалён

2021-09-10 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/09/21 - 09/09/21
Work session total: 2:20:31
Billable: Yes

Grand total: 2:20:31

2021-09-11 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/10/21 - 09/10/21
Work session total: 0:07:01
Billable: Yes

Grand total: 2:27:32

2021-09-16 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/15/21 - 09/15/21
Work session total: 0:31:45
Billable: Yes

Grand total: 2:59:17

2021-09-17 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/16/21 - 09/16/21
Work session total: 1:02:05
Billable: Yes

Grand total: 4:01:22

2021-09-20 05:35 UTC, trojikman requested changes
Получаю такую ошибку, когда пытаюсь удалить таск:
<details>

```
odoo_1  | 2021-09-20 05:33:09,329 16 ERROR deb odoo.http: Exception during JSON request handling. 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
odoo_1  |     result = request.dispatch()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
odoo_1  |     result = self._call_function(**self.params)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 359, in _call_function
odoo_1  |     return checked_call(self.db, *args, **kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
odoo_1  |     return f(dbname, *args, **kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 347, in checked_call
odoo_1  |     result = self.endpoint(*a, **kw)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 912, in __call__
odoo_1  |     return self.method(*args, **kw)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 531, in response_wrap
odoo_1  |     response = f(*args, **kw)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1389, in call_kw
odoo_1  |     return self._call_kw(model, method, args, kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
odoo_1  |     return call_kw(request.env[model], method, args, kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
odoo_1  |     result = _call_kw_multi(method, model, args, kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
odoo_1  |     result = method(recs, *args, **kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/models.py", line 3663, in write
odoo_1  |     field.write(self, vals[fname])
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3046, in write
odoo_1  |     return self.write_batch([(records, value)])
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3067, in write_batch
odoo_1  |     return self.write_real(records_commands_list, create)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3239, in write_real
odoo_1  |     flush()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 3199, in flush
odoo_1  |     comodel.browse(to_delete).unlink()
odoo_1  |   File "/mnt/addons/sync-addons/sync/models/sync_task.py", line 179, in unlink
odoo_1  |     self.with_context(active_test=False).mapped("cron_ids").unlink()
odoo_1  |   File "/mnt/addons/sync-addons/sync/models/sync_trigger_cron.py", line 24, in unlink
odoo_1  |     self.mapped("cron_id").unlink()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 307, in unlink
odoo_1  |     self._try_lock()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 295, in _try_lock
odoo_1  |     [tuple(self.ids)], log_exceptions=False)
odoo_1  |   File "<decorator-gen-3>", line 2, in execute
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 101, in check
odoo_1  |     return f(self, *args, **kwargs)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 298, in execute
odoo_1  |     res = self._obj.execute(query, params)
odoo_1  | Exception
odoo_1  | 
odoo_1  | The above exception was the direct cause of the following exception:
odoo_1  | 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 639, in _handle_exception
odoo_1  |     return super(JsonRequest, self)._handle_exception(exception)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 315, in _handle_exception
odoo_1  |     raise exception.with_traceback(None) from new_cause
odoo_1  | psycopg2.ProgrammingError: syntax error at or near ")"
odoo_1  | LINE 1: SELECT id FROM "ir_cron" WHERE id IN () FOR UPDATE NOWAIT
```

</details>

2021-09-20 06:55 UTC, yelizariev commented
> Получаю такую ошибку, когда пытаюсь удалить таск:

Похоже на проблему в коде оду, но придется подстроиться

2021-09-20 06:58 UTC, yelizariev commented
@trojikman попровали. Комиты объединить потом надо будет

2021-09-21 04:00 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/20/21 - 09/20/21
Work session total: 0:29:31
Billable: Yes

Grand total: 4:30:53

2021-09-21 06:45 UTC, trojikman approved these changes

2021-09-21 06:56 UTC, trojikman commented
I approve to merge it now

2021-09-21 06:56 UTC, merged

2021-09-21 06:59 UTC, trojikman commented
via Hubstaff
User: Denis Mudarisov

Project: sync-addons - https://app.hubstaff.com/projects/1618283
Date Range: 09/20/21 - 09/21/21
Work session total: 0:46:49
Billable: Yes

Grand total: 5:17:42