[FIX] sync_telegram: blocked bot handler
itpp-labs/sync-addons pull request #391
Opened 2021-12-24 07:59 UTC by BykovVik

2021-12-24 10:04 UTC, em230418 requested changes
Помимо замачений ниже, есть и общее замечания.
1. Тут строго форматированием кода. Перед коммитом выполни `pre-commit run --all`. Если нету pre-commit то надо установить. Если все пункты будут "Passed", то делай коммит.
2. Я скидывал справочник по оформлению коммитов. https://gitlab.com/itpp/handbook/blob/master/documenting-updates.md
В данном случае надо использовать `:ambulance:`. Я бы назвал `:ambulance: sync_telegram: handle case, where user blocked bot`.
3. Надо поднять минорную версию (в примере x.y.z минорная версия - это z). и описать изменение в doc/changelog.rst.

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +
Занеси это в метод `_eval_context_telegram`.
Соотвественно исправь там, где ты используешь alert_message_body.

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +                                    author_id=kwargs['odoobot_id'], message_type="comment", subtype_xmlid="mail.mt_comment")
Используй заготовленный метод: https://github.com/itpp-labs/sync-addons/blob/d52d791a0de39ec9c26bf6400c03490ec9329a0e/multi_livechat/tools.py#L74-L81
При использовании такого метода отпадает необходимость передавать odoobot_id.

Заготовленный метод будет доступен в объекте multi_livechat_context. Пример, как такой объект получить:
https://github.com/itpp-labs/sync-addons/blob/d52d791a0de39ec9c26bf6400c03490ec9329a0e/sync_viber/models/sync_project.py#L106-L110

Потом вызываешь примерно так multi_livechat_context.post_channel_message(...)

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +            except:
Просто except не надо ставить. Надо обрабатывать конкретное исключение, которое выскакивает. Какое именно - можно посмотреть в обломаных Job-ах.

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +                                    author_id=kwargs['odoobot_id'], message_type="comment", subtype_xmlid="mail.mt_comment")
Про except и post_channel_message отписал выше

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +                                    author_id=kwargs['odoobot_id'], message_type="comment", subtype_xmlid="mail.mt_comment")
Про except и post_channel_message отписал выше

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/data/mail_sync_project_data.xml
> +                    telegram.sendMessage(telegram_user_ref, message_html, parse_mode='HTML', channel=channel, odoobot_id=odoobot_id)
odoobot_id не надо. См. подробности в комментах к файлу sync_project.py

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/data/mail_sync_project_data.xml
> +                                telegram.sendPhoto(telegram_user_ref, attach.datas, channel=channel, odoobot_id=odoobot_id)
odoobot_id не надо. См. подробности в комментах к файлу sync_project.py

2021-12-24 10:04 UTC, em230418 commented on sync_telegram/data/mail_sync_project_data.xml
> +                                telegram.sendDocument(telegram_user_ref, attach.name, attach.datas, channel=channel, odoobot_id=odoobot_id)
odoobot_id не надо. См. подробности в комментах к файлу sync_project.py

2021-12-27 05:22 UTC, em230418 requested changes
Еще замечания:
1. Добавь себя в https://github.com/itpp-labs/sync-addons/tree/14.0/sync_telegram#contributors (можно со ссылкой на профиль в Гитхаюе)
2. первый коммит соедени со вторым
И замечания ниже.

2021-12-27 05:22 UTC, em230418 commented on sync_telegram/models/sync_project.py
> +                    chat_id, _html_sanitize_telegram(html), *args, kwargs["parse_mode"]
**kwargs превратился в kwargs["parsemode"]. Случайно или намеренно? Если намеренно то надо пояснить

2021-12-28 09:13 UTC, em230418 commented on sync_telegram/doc/changelog.rst
> +`4.1.1`
На первой и шестой строке убери пробелы, пожалуйста. В скрине они подствечены красным
![Снимок экрана_2021-12-28_14-11-57](https://user-images.githubusercontent.com/52414052/147549914-700ad680-2bec-4cd9-bc22-46f3fffbbb5a.png)

2021-12-28 09:30 UTC, em230418 approved these changes

2021-12-28 10:19 UTC, yelizariev approved these changes

2022-01-03 14:59 UTC, yelizariev commented
I approve to merge it now

2022-01-03 14:59 UTC, merged