11.0 Merge from 10.0
itpp-labs/sync-addons pull request #51
Opened 2019-10-09 07:54 UTC by fedoranvar

2019-10-09 08:13 UTC, Ramil-Mukhametzyanov requested changes
OSError: File not found: openapi/views/tour_views.xml

2019-10-09 08:52 UTC, Ramil-Mukhametzyanov requested changes
![image](https://user-images.githubusercontent.com/33877236/66466363-fef7e480-ea9b-11e9-9fd5-5bcf1760d738.png)

2019-10-09 09:16 UTC, Ramil-Mukhametzyanov commented on openapi/doc/changelog.rst
> +- **Improvement:** Security rules for reading and configuration
:+1: checked

2019-10-09 09:39 UTC, Ramil-Mukhametzyanov commented on openapi/doc/changelog.rst
> +- **Fix:** Translation model's float-field into JSON's integer
:+1: checked

2019-10-09 11:13 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-10 08:43 UTC, yelizariev approved these changes

2019-10-10 08:43 UTC, yelizariev commented
I approve to merge it now

2019-10-10 08:43 UTC, merged