12.0 merge from 11.0
itpp-labs/sync-addons pull request #52
Opened 2019-10-10 08:54 UTC by fedoranvar

2019-10-15 09:38 UTC, Ramil-Mukhametzyanov commented on openapi/doc/changelog.rst
> +- **Fix:** Translation model's float-field into JSON's integer
:+1: checked

2019-10-15 09:45 UTC, Ramil-Mukhametzyanov requested changes
User with OpenAPI role User can edit API fields: name, description, Log requests and Log responds.

2019-10-15 13:08 UTC, Ramil-Mukhametzyanov approved these changes

2019-10-16 12:42 UTC, em230418 commented
1. Тесты через odooup не запускаются

Предлагаю сделать это для исправления (во всех файлах с тестами):
```diff
iff --git a/openapi/tests/test_api.py b/openapi/tests/test_api.py
index 81e237b..96432a1 100644
--- a/openapi/tests/test_api.py
+++ b/openapi/tests/test_api.py
@@ -5,6 +5,7 @@ import requests
 import logging
 
 from odoo import api
+from odoo.tests import tagged
 from odoo.tests.common import HttpCase, PORT, get_db_name
 
 from ..controllers import pinguin
@@ -20,10 +21,8 @@ MESSAGE = 'message is posted from API'
 # * /res.partner/call/{method_name} (without recordset)
 # * /res.partner/{record_id}
 
+@tagged('post_install', 'at_install')
 class TestAPI(HttpCase):
-    at_install = True
-    post_install = True
-
     def setUp(self):
         super(TestAPI, self).setUp()
         self.db_name = get_db_name()
```

2. В самом test_api обламывается этот метод
```
FAIL: test_call_allowed_method_on_singleton_record (odoo.addons.openapi.tests.test_api.TestAPI) 
Traceback (most recent call last): 
`   File "/opt/odoo/vendor/it-projects-llc/sync-addons/openapi/tests/test_api.py", line 140, in test_call_allowed_method_on_singleton_record 
`     self.assertEqual(resp.status_code, pinguin.CODE__success) 
` AssertionError: 501 != 200 
```

501 - это какой-то метод нереализован. Полагаю, мне надо какой-то модуль установить, чтобы заработало. Тут предлагаю выяснить какого модуля не хватает, чтобы метод заработал. Перед выполнением теста проверить наличие этого модуля. Если нету - выполнить `self.skipTest`. В идеале - использовать методы из модулей, которые являются зависимостями openapi.

Для воспроизводства всего этого я делал следующее:
```
docker-compose run dodoo -- init --new-database sync52 --demo -m web_tour,base,web,web_settings_dashboard,openapi  # установка модулей с зависимостями
docker-compose run odoo -d sync52 --test-enable --stop-after-init -i openapi  # запуск теста с зависимостями
```

2019-10-17 14:15 UTC, yelizariev commented
@em230418 do you add openapi to the --load ?

2019-10-18 05:59 UTC, em230418 commented
> @em230418 do you add openapi to the --load ?

Добавил. Проблемы такие-же

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 976dc12..3e2defb 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -87,7 +87,7 @@ services:
   odoo:
     << : *default-odoo
     entrypoint: ['/entrypoint.sh']
-    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml']
+    command: ['--dev', 'wdb,reload,qweb,werkzeug,xml', '--load', 'openapi']
     depends_on: ['db', 'wdb', 'proxy', 'smtpfake']
 
   # http://odoo.localhost
```

2019-10-18 06:21 UTC, fedoranvar commented
> 1. Тесты через odooup не запускаются
> 
> Предлагаю сделать это для исправления (во всех файлах с тестами):
> 
> ```diff
> iff --git a/openapi/tests/test_api.py b/openapi/tests/test_api.py
> index 81e237b..96432a1 100644
> --- a/openapi/tests/test_api.py
> +++ b/openapi/tests/test_api.py
> @@ -5,6 +5,7 @@ import requests
>  import logging
>  
>  from odoo import api
> +from odoo.tests import tagged
>  from odoo.tests.common import HttpCase, PORT, get_db_name
>  
>  from ..controllers import pinguin
> @@ -20,10 +21,8 @@ MESSAGE = 'message is posted from API'
>  # * /res.partner/call/{method_name} (without recordset)
>  # * /res.partner/{record_id}
>  
> +@tagged('post_install', 'at_install')
>  class TestAPI(HttpCase):
> -    at_install = True
> -    post_install = True
> -
>      def setUp(self):
>          super(TestAPI, self).setUp()
>          self.db_name = get_db_name()
> ```
> 
> 1. В самом test_api обламывается этот метод
> 
> ```
> FAIL: test_call_allowed_method_on_singleton_record (odoo.addons.openapi.tests.test_api.TestAPI) 
> Traceback (most recent call last): 
> `   File "/opt/odoo/vendor/it-projects-llc/sync-addons/openapi/tests/test_api.py", line 140, in test_call_allowed_method_on_singleton_record 
> `     self.assertEqual(resp.status_code, pinguin.CODE__success) 
> ` AssertionError: 501 != 200 
> ```
> 
> 501 - это какой-то метод нереализован. Полагаю, мне надо какой-то модуль установить, чтобы заработало. Тут предлагаю выяснить какого модуля не хватает, чтобы метод заработал. Перед выполнением теста проверить наличие этого модуля. Если нету - выполнить `self.skipTest`. В идеале - использовать методы из модулей, которые являются зависимостями openapi.
> 
> Для воспроизводства всего этого я делал следующее:
> 
> ```
> docker-compose run dodoo -- init --new-database sync52 --demo -m web_tour,base,web,web_settings_dashboard,openapi  # установка модулей с зависимостями
> docker-compose run odoo -d sync52 --test-enable --stop-after-init -i openapi  # запуск теста с зависимостями
> ```

1) Тесты могут не запускаться из-за отсутствия питоновских-зависимостей: "bravado-core", "swagger-spec-validator" (см. манифест)
Способы решения: 
* пересобрать образ и в докерфайл включить:
USER ROOT
RUN pip3 install {python_packages} --no-cache-dir
* или зайти в контейнер и в ручную на время сессии установить

2) Нашёл причину:
В 12й версии у res.partner нету метода message_post - потому и ругается
Метод с аналогичным названием есть в модели [mail.thread]

2019-10-18 06:35 UTC, em230418 commented
>     1. Тесты могут не запускаться из-за отсутствия питоновских-зависимостей: "bravado-core", "swagger-spec-validator" (см. манифест)
>        Способы решения:
>        а) пересобрать образ и в докерфайл включить:
>        USER ROOT
>        RUN pip3 install {python_packages} --no-cache-dir
>        б) или зайти в контейнер и в ручную на время сесс

Они уже установлены. Без них невозможно было установить модуль.

>     2.  Нашёл причину:
>         В 12й версии у res.partner нету метода message_post - потому и ругается
>         Метод с аналогичным названием есть в модели [mail.thread]
>         Предлагаемые решения:
>         а) Поправить код, чтобы логика сохранилась (отправка сообщения от партнёра)
>         б) Поменять сценарий теста
>         в) Пропустить этот тест в этом ПР

Я за вариант (а) но с упоминанием, что тест пропущен из-за отсутсвия такого-то (mail) модуля (используя упомянутый skipTest).

2019-10-18 06:39 UTC, fedoranvar commented
> > ```
> > 1. Тесты могут не запускаться из-за отсутствия питоновских-зависимостей: "bravado-core", "swagger-spec-validator" (см. манифест)
> >    Способы решения:
> >    а) пересобрать образ и в докерфайл включить:
> >    USER ROOT
> >    RUN pip3 install {python_packages} --no-cache-dir
> >    б) или зайти в контейнер и в ручную на время сесс
> > ```
> 
> Они уже установлены. Без них невозможно было установить модуль.
> 
> > ```
> > 2.  Нашёл причину:
> >     В 12й версии у res.partner нету метода message_post - потому и ругается
> >     Метод с аналогичным названием есть в модели [mail.thread]
> >     Предлагаемые решения:
> >     а) Поправить код, чтобы логика сохранилась (отправка сообщения от партнёра)
> >     б) Поменять сценарий теста
> >     в) Пропустить этот тест в этом ПР
> > ```
> 
> Я за вариант (а) но с упоминанием, что тест пропущен из-за отсутсвия такого-то (mail) модуля (используя упомянутый skipTest).

1) Не через одуап тесты запускаются (проверено у себя)
2)" ... что тест пропущен из-за отсутсвия такого-то (mail) модуля..." - так пропустить тест, если да, то это вариант (В)

2019-10-18 07:21 UTC, em230418 commented
> 1. Не через одуап тесты запускаются (проверено у себя)

Судя по всему, тесты были запущены при установке модуля (поведение по-умолчанию, если оду при установки также использовали что-то вроде --tests-enabled).

> Subclasses of odoo.tests.common.BaseCase (usually through TransactionCase, SavepointCase or HttpCase) are automatically tagged with standard, at_install and their source module’s name by default.

> at_install: Means that the test will be executed right after the module installation and before other modules are installed. This is a default implicit tag.

https://www.odoo.com/documentation/12.0/reference/testing.html#test-selection

В этой-же документации сказано, что post_install - это возможность запустить тесты после установки:

> post_install: Means that the test will be executed after all the modules are installed. This is what you want for HttpCase tests most of the time.

Судя по наличие в коде `post_install = True` тут задумывалось, что тесты будут запускаться после установки модуля. Но в моем случае не срабатывает. А должно, т.к. тесты я запускаю после установки модуля.

В той-же документации сказано, что для отметок флагов вида "at_install", "post_install" надо использовать декоратор tagged.

Обо всем этом узнал только-что :smile: 

> 2)" ... что тест пропущен из-за отсутсвия такого-то (mail) модуля..." - так пропустить тест, если да, то это вариант (В)

Вариант (в) воспринял как "ничего не менять".

Паралельно, я остановил модуль mail, и убедился, что тест с успехом выполняется. Вообщем в таком случае можно просто добавить проверку, что какой-то модуль установлен, и пропускать тест, если не установлен.

2019-10-18 07:54 UTC, fedoranvar commented
> > 1. Не через одуап тесты запускаются (проверено у себя)
> 
> Судя по всему, тесты были запущены при установке модуля (поведение по-умолчанию, если оду при установки также использовали что-то вроде --tests-enabled).
> 
> > Subclasses of odoo.tests.common.BaseCase (usually through TransactionCase, SavepointCase or HttpCase) are automatically tagged with standard, at_install and their source module’s name by default.
> 
> > at_install: Means that the test will be executed right after the module installation and before other modules are installed. This is a default implicit tag.
> 
> https://www.odoo.com/documentation/12.0/reference/testing.html#test-selection
> 
> В этой-же документации сказано, что post_install - это возможность запустить тесты после установки:
> 
> > post_install: Means that the test will be executed after all the modules are installed. This is what you want for HttpCase tests most of the time.
> 
> Судя по наличие в коде `post_install = True` тут задумывалось, что тесты будут запускаться после установки модуля. Но в моем случае не срабатывает. А должно, т.к. тесты я запускаю после установки модуля.
> 
> В той-же документации сказано, что для отметок флагов вида "at_install", "post_install" надо использовать декоратор tagged.
> 
> Обо всем этом узнал только-что 
> 
> > 2)" ... что тест пропущен из-за отсутсвия такого-то (mail) модуля..." - так пропустить тест, если да, то это вариант (В)
> 
> Вариант (в) воспринял как "ничего не менять".
> 
> Паралельно, я остановил модуль mail, и убедился, что тест с успехом выполняется. Вообщем в таком случае можно просто добавить проверку, что какой-то модуль установлен, и пропускать тест, если не установлен.

Добавил обработку наличия модуля 'mail'. 

Метод SkipTest находится в классе unittest, который не используется в тестах оду, потому я обыкновенно написал принт с причиной пропуска теста

2019-10-18 08:16 UTC, em230418 commented
> Метод SkipTest находится в классе unittest, который не используется в тестах оду

Примеры применения:

В 12-ой версии:
```
./addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py:54:            raise unittest.SkipTest('Skip this test as it works only with %s (%s loaded)' % (generic_coa.name, chart_of_accounts.name))
./addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py:107:            raise unittest.SkipTest('Skip this test as it works only with %s (%s loaded)' % (generic_coa.name, chart_of_accounts.name))
./addons/account/tests/account_test_classes.py:21:            self.skipTest("No Chart of account found")
```

В 13-ой версии чуть больше:
```
./addons/stock/tests/test_quant.py:204:            self.skipTest('Cannot test concurrent transactions without demo data.')
./addons/stock/tests/test_quant.py:293:            self.skipTest('Cannot test concurrent transactions without demo data.')
./addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py:54:            raise unittest.SkipTest('Skip this test as it works only with %s (%s loaded)' % (generic_coa.name, chart_of_accounts.name))
./addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py:107:            raise unittest.SkipTest('Skip this test as it works only with %s (%s loaded)' % (generic_coa.name, chart_of_accounts.name))
./addons/account/tests/account_test_savepoint.py:22:            cls.skipTest("Accounting Tests skipped because the user's company has no chart of accounts.")
./addons/account/tests/account_test_classes.py:21:            self.skipTest("No Chart of account found")
```

2019-10-18 08:18 UTC, em230418 commented on openapi/tests/test_api.py
> +            print("\n\n[INFO]: To run test 'test_call_allowed_method_on_singleton_record' install 'mail' module\n\n")
Практикуется использовать _logger.info https://github.com/odoo/odoo/blob/9d0f172f29085a6b164313bf20178270b9572cc2/addons/payment_paypal/controllers/main.py#L7

2019-10-18 08:19 UTC, em230418 commented on openapi/tests/test_api.py
> +        # import wdb;wdb.set_trace()
Предлагаю убрать это

2019-10-18 11:01 UTC, em92 commented on openapi/tests/test_api.py
> +            unittest.raise.SkipTest("To run test 'test_call_allowed_method_on_singleton_record' install 'mail'-module")
Можно просто `self.skipTest("....")`

2019-10-18 11:02 UTC, em230418 commented on openapi/tests/test_api.py
> +            unittest.raise.SkipTest("To run test 'test_call_allowed_method_on_singleton_record' install 'mail'-module")
Можно просто self.skipTest("To run test...")

2019-10-18 12:33 UTC, yelizariev commented
Нашел заметку про мейл. 
https://github.com/it-projects-llc/sync-addons/blame/72636b4426fdfc5cc5acf8d1390875bc0c0787e0/openapi/README.rst#L29

Там написано, что надо бы переделать и другой методв использовать

2019-10-22 08:40 UTC, em230418 commented
I approve to merge it now

2019-10-22 08:40 UTC, merged