:one::three::tada: Init commit
itpp-labs/sync-addons pull request #64
Opened 2019-12-02 10:58 UTC by fedoranvar

2019-12-05 13:36 UTC, yelizariev commented on base_api/README.rst
> +Models and controllers for basic functionality
В модуле не планируется контроллеры

2019-12-05 13:36 UTC, yelizariev commented on base_api/README.rst
> +basic function and methods of API for openapi or XML-RPC
```suggestion
Basic methods of API for openapi or XML-RPC
```

2019-12-05 13:36 UTC, yelizariev commented on base_api/__manifest__.py
> +    "summary": """basic function and methods of API for openapi or XML-RPC""",
С большой буквы

2019-12-05 13:36 UTC, yelizariev commented on base_api/doc/index.rst
> +{Optional section for uninstallation notes. Delete it if you don't have notes for uninstallation.}
![удоли](https://user-images.githubusercontent.com/186131/69955891-86078d00-1520-11ea-994a-4201eb6f9fcf.jpg)

2019-12-05 13:44 UTC, yelizariev requested changes

2019-12-05 13:44 UTC, yelizariev commented on base_api/README.rst
> +**base.py** - extends *base*-model with functions like:
It's better to say "adds following methods to all models"

2019-12-05 13:44 UTC, yelizariev commented on base_api/README.rst
> +    *It checks if there are records that satisfies required `vals`, if there is, then it return they* `ids` *else creates one and returns it id*
fix formatting
![image](https://user-images.githubusercontent.com/186131/70240392-f7e50e00-178e-11ea-89e5-6f14ab3b96fc.png)

2019-12-05 13:44 UTC, yelizariev commented on base_api/README.rst
> +    **note**: for x2many and many2one fields creation didn't work
x2many: Создание работает. Поиск не работает. 

many2one: работает для айди передавать

2019-12-05 13:44 UTC, yelizariev commented on base_api/README.rst
> +    * searches for records with selected fields with values (``vals``)
Про это уже написано выше

2019-12-05 13:44 UTC, yelizariev commented on base_api/README.rst
> +    **note**: for x2many and many2one fields creation didn't work
И надо писать что означает "не работает"

2019-12-12 09:01 UTC, yelizariev commented on base_api/__init__.py
> +    # make import in post_load to avoid applying monkey patches when this
There are no monkey patches in this module

2019-12-12 09:14 UTC, yelizariev requested changes

2019-12-12 09:14 UTC, yelizariev commented on base_api/controllers/pinguin.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
No need to put this in in controllers folder

2019-12-12 09:14 UTC, yelizariev commented on base_api/controllers/pinguin.py
> +    return result
You must delete copy-pasted code from openapi module

2019-12-12 09:14 UTC, yelizariev commented on base_api/doc/index.rst
> +Use it with such models as like as OpenAPI
OpenAPI is not a model.
Don't forget about buit-in XML RPC

2019-12-12 09:14 UTC, yelizariev commented on base_api/tests/test_base.py
> +        partner_obj.search([('name', '=', t_name)]).unlink()
You delete records here, but don't it with next tests

            'name': 'TestParent',


Why?

2019-12-13 07:30 UTC, yelizariev reviewed
Добавь base_api   в зависимости openapi

2019-12-13 07:34 UTC, yelizariev requested changes
Надо описание функций перенести в index.rst всё таки. Иначе в магазине пусто будет

2019-12-13 07:40 UTC, yelizariev requested changes

2019-12-13 07:40 UTC, yelizariev commented on base_api/doc/index.rst
> +* Can be used in built-in XML RPC
Вот что надо написать: 

_методы предназначенные для вызова извне через апи (например через Опеапи или РПЦ)_

Далее сделать заголовок Методы и перенести описание методов из РИДМИ

2019-12-13 07:41 UTC, yelizariev commented on base_api/controllers/pinguin.py
> +# pyling: disable=redefined-builtin
Верни лицензию

2019-12-19 10:39 UTC, yelizariev requested changes
* I'm not sure that the icon is correct

2019-12-19 10:39 UTC, yelizariev commented on openapi/doc/index.rst
> +  + Note: Skipping of this step may lead to ignorance of a first request by
Проверяй форматирование

![screenshot-github com-2019 12 19-15_07_33](https://user-images.githubusercontent.com/186131/71164643-50c5a380-2271-11ea-82f3-45ddba8a48fa.png)

2019-12-19 10:39 UTC, yelizariev commented on openapi/doc/index.rst
> +  + Note: Skipping of this step may lead to ignorance of a first request by
Ты не написал какая именно ошибка

2019-12-19 10:39 UTC, yelizariev commented on base_api/static/description/index.html
> +    please add some information
:-1:

2019-12-19 10:39 UTC, yelizariev commented on base_api/doc/index.rst
> +      - e.g. `fields = [ company_id, company_id.name ]`
Еще отличие в новом аргументе delimeter

2019-12-19 10:39 UTC, yelizariev commented on base_api/doc/index.rst
> +      - e.g. `fields = [ company_id, company_id.name ]`
Либо сделай точку по умолчанию для разделителя, либо примеры поменяй на слеш

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +                                    record_for_replace = ird_object.xmlid_lookup(id_prefix + '.' + record_for_replace)[2]
Слишком много вложений. Переделай как-нибудь

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +        id_prefix = '__base_api__'
consts must be at the beginning of the file

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +                'module': '__base_api__',
you have to use the const here

2019-12-19 10:39 UTC, yelizariev commented on base_api/lib/pinguin.py
> +# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl.html).
Добавь свои и оригинальные копирайты

2019-12-19 10:39 UTC, yelizariev commented on base_api/doc/index.rst
> +        (4, 'ext.child_2', 0)] }`
Для кода делай соответствующее форматирование

![screenshot-github com-2019 12 19-15_34_23](https://user-images.githubusercontent.com/186131/71166694-16f69c00-2275-11ea-9aa0-4692d626c765.png)

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +                raise ValueError('No external id for %s' % (field))
Непонятно что это значит. Не записи с таким айди или вместо айди-строки получили числи или вообще там пусто?

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +            raise ValueError('External ID is not defined')
Описание ошибки не очень. У тебя в документации про это по другому совсем написано:


      - Must contain `id` field type of *string*

2019-12-19 10:39 UTC, yelizariev commented on base_api/models/base.py
> +                raise ValueError('No external id for %s' % (field))
Если речь про то, что по айди-строке не нашли запись, то желательно писать чему равна эта строка -- в одном поле может несколько строк быть

2019-12-19 14:42 UTC, yelizariev commented on base_api/models/base.py
> +        # Yes: Write changes to record
I'd prefer to put it inside the block

2019-12-25 09:52 UTC, fedoranvar commented on base_api/models/base.py
> +                raise ValueError('No external id for %s' % (field))
речь о том, что по айди-строке не нашли. Чтобы не плодить вложенность, я оставлю только один try, но переделаю сообще об ошибке

2019-12-25 10:09 UTC, fedoranvar commented on base_api/models/base.py
> +                                    record_for_replace = ird_object.xmlid_lookup(id_prefix + '.' + record_for_replace)[2]
разделил на два цикла

2019-12-25 13:48 UTC, fedoranvar commented on base_api/doc/index.rst
> +        (4, 'ext.child_2', 0)] }`
чек

2019-12-30 09:47 UTC, yelizariev requested changes

2019-12-30 09:47 UTC, yelizariev commented on base_api/static/description/index.html
> +    please add some information
Don't cheat check for documentation

2020-01-13 08:18 UTC, yelizariev requested changes

2020-01-13 08:18 UTC, yelizariev commented on openapi/security/ir.model.access.csv
> +user_access_openapi_access_create_context,access_openapi_access_create_context,model_openapi_access_create_context,openapi.group_user,1,1,1,0
https://github.com/it-projects-llc/sync-addons/pull/69#discussion_r361938806

2020-02-18 08:26 UTC, yelizariev commented
Этот комит надо объединить с комитов создания модуля

> rainbow refactoring due to creation of 'base_api' module

Там никакой не рефакторинг, а удаление кода

2020-02-18 08:30 UTC, yelizariev commented
Да и изменение цены отдельно не желательно делать. Это всё часть одного большого изменения, которое нужно вместе принимать, вместе переносить в другие ветки и т.д.

2020-02-18 08:52 UTC, KolushovAlexandr approved these changes

2020-02-18 12:53 UTC, yelizariev commented
# [Codecov](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=h1) Report
> Merging [#64](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=desc) into [13.0](https://codecov.io/gh/itpp-labs/sync-addons/commit/e79057133d8cd548f4fe1e85db06e80959d31b3b&el=desc) will **increase** coverage by `3.64%`.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/itpp-labs/sync-addons/pull/64/graphs/tree.svg?width=650&height=150&src=pr&token=GwjhtrwSXC)](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##             13.0      #64      +/-   ##
==========================================
+ Coverage   74.32%   77.97%   +3.64%     
==========================================
  Files          16       17       +1     
  Lines        1071     1212     +141     
==========================================
+ Hits          796      945     +149     
+ Misses        275      267       -8     
```

| Flag | Coverage Δ | |
|---|---|---|
| #backend | `77.97% <91.31%> (+3.64%)` | :arrow_up: |
| #controllers | `77.97% <91.31%> (+3.64%)` | :arrow_up: |
| #res_config | `77.97% <91.31%> (+3.64%)` | :arrow_up: |
| #tests | `77.97% <91.31%> (+3.64%)` | :arrow_up: |

| [Impacted Files](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [base\_api/tests/test\_base.py](https://codecov.io/gh/itpp-labs/sync-addons/pull/64/diff?src=pr&el=tree#diff-YmFzZV9hcGkvdGVzdHMvdGVzdF9iYXNlLnB5) | `100.00% <0.00%> (ø)` | |
| [base\_api/models/base.py](https://codecov.io/gh/itpp-labs/sync-addons/pull/64/diff?src=pr&el=tree#diff-YmFzZV9hcGkvbW9kZWxzL2Jhc2UucHk=) | `88.88% <0.00%> (ø)` | |
| [base\_api/lib/pinguin.py](https://codecov.io/gh/itpp-labs/sync-addons/pull/64/diff?src=pr&el=tree#diff-YmFzZV9hcGkvbGliL3Bpbmd1aW4ucHk=) | `85.03% <0.00%> (ø)` | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=footer). Last update [e790571...8665077](https://codecov.io/gh/itpp-labs/sync-addons/pull/64?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

2020-02-18 14:20 UTC, yelizariev approved these changes
Looks good

2020-02-19 08:02 UTC, closed without merging